alias: sunscreen_bepaling
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: state
    entity_id: input_boolean.sunscreen_set_manual
    state: "off"
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.sunscreen_max_wind_gust
                state: "True"
              - condition: state
                entity_id: sensor.sunscreen_min_inside_temp
                state: "True"
              - condition: state
                entity_id: sensor.sunscreen_min_outdoor_temp
                state: "True"
              - condition: state
                entity_id: sensor.sunscreen_max_rain_next_hour
                state: "True"
              - condition: state
                entity_id: sensor.sunscreen_time_frame_for_execution
                state: "True"
              - condition: state
                entity_id: sensor.sunscreen_irradiance
                state: "True"
              - condition: state
                entity_id: sensor.sunscreen_months_for_execution
                state: "True"
              - condition: numeric_state
                entity_id: sensor.buienradar_precipitation_forecast_average
                below: input_number.sunscreen_set_regen
              - condition: sun
                before: sunset
                after: sunrise
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.sunscreen_conditions_down
    default:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.sunscreen_conditions_down
mode: single
