alias: sunscreen_google_sheet
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: sun
    before: sunset
    after: sunrise
action:
  - service: google_sheets.append_sheet
    data:
      config_entry: c2f8b2b921c84706b75f3b2d1bbf97ad
      data:
        Date: "{{ now().strftime('%-d-%b-%y') }}"
        Smanual: "{{ states('input_boolean.sunscreen_set_manual') }}"
        rain_next_hour: "{{ states('sensor.buienradar_precipitation_forecast_total') }}"
        Srain_next_hour: "{{ states('input_number.sunscreen_set_regen') }}"
        wind_gust: "{{ states('sensor.buienradar_wind_speed')}}"
        Swind_gust: "{{ states('input_number.sunscreen_set_windsnelheid')}}"
        Temp_Min_inside: "{{ states('sensor.buienradar_temperature') }}"
        STemp_Min_inside: "{{ states('input_number.sunscreen_set_min_inside_temp') }}"
        Temp_min_outside: "{{ states('sensor.woonkamer_temperature') }}"
        STemp_min_outside: "{{ states('input_number.sunscreen_set_min_outside_temp') }}"
        irradiance: "{{ states('sensor.buienradar_irradiance') }}"
        Sirradiance: "{{ states('input_number.sunscreen_set_irradiance') }}"
        45minNiet_getriggered: " {% if ( as_timestamp(now()) - as_timestamp(states.input_boolean.sunscreen_conditions_down.last_changed) |int(0) ) > 2700 %} True {% else %} False {% endif %}"
mode: single
